Add unit test coverage gate; coverage-html make path

diff --git a/.github/workflows/pre-main.yml b/.github/workflows/pre-main.yml
--- a/.github/workflows/pre-main.yml
+++ b/.github/workflows/pre-main.yml
@@ -24,3 +24,19 @@ jobs:
 
       - name: Run Tests
         run: make generate-golang-schema build tests
+
+      - name: Quality Gate - Test coverage shall be above threshold
+        env:
+          TESTCOVERAGE_THRESHOLD: 40
+        run: |
+          echo "Quality Gate: checking test coverage is above threshold ..."
+          echo "Threshold             : $TESTCOVERAGE_THRESHOLD %"
+          totalCoverage=`go tool cover -func=cover.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
+          echo "Current test coverage : $totalCoverage %"
+          if (( $(echo "$totalCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print ($1 > $2)}') )); then
+              echo "OK"
+          else
+              echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
+              echo "Failed"
+              exit 1
+          fi
